In [26]:
import numpy as np

c = np.ones((5,5), dtype=np.uint8)
b = np.array((1,2,3,4,5))
print b
print a

c[0:1,:]=b
i=2
if(1 < i < 3):
    print "OK"
print c

def traverse_kargs(**kwargs):
    for k, v in kwargs.items():
        print(k, v)
traverse_kargs(fighter1='Fedor', fighter2='Randleman')
traverse_kargs(one=1, two=2)

str = 'I like {}, Do not like {}'
print str.format('Apple', 'Saming')


[1 2 3 4 5]
0
OK
[[1 2 3 4 5]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
('fighter1', 'Fedor')
('fighter2', 'Randleman')
('two', 2)
('one', 1)
I like Apple, Do not like Saming
I like {}, Do not like {}


In [33]:
a = np.arange(24).reshape((2, 3, 4))
print a
b = a[...,1]
print b
g = np.split(np.arange(9), 3)
print g[0]

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[ 1  5  9]
 [13 17 21]]
[0 1 2]


In [52]:
l0 = np.arange(6).reshape((2, 3))
l1 = np.arange(6,12).reshape((2,3))
print l0
print l1
print np.concatenate((l0,l1), 0)
s = np.stack((l0, l1))

print s
print s.shape
t = s.transpose(2,1,0)
print t
print t.shape

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
(2, 2, 3)
[[[ 0  6]
  [ 3  9]]

 [[ 1  7]
  [ 4 10]]

 [[ 2  8]
  [ 5 11]]]
(3, 2, 2)
